return {
  -- {
  --   "saghen/blink.cmp",
  --   dependencies = {
  --     {
  --       "saghen/blink.lib",
  --       build = "echo 'blink.lib downloaded'",
  --     },
  --   },
  --   opts = {
  --       keymap = { preset = 'super-tab' },
  --       appearance = {
  --         nerd_font_variant = 'mono',
  --       },
  --       completion = {
  --         documentation = { auto_show = false },
  --         menu = {
  --           draw = {
  --             columns = { { "kind_icon" }, { "label", "label_description", gap = 1 } },
  --           },
  --         },
  --       },
  --       sources = {
  --         default = { 'lsp', 'path', 'snippets', 'buffer' },
  --       },
  --       fuzzy = { implementation = 'prefer_rust' },
  --   },
  -- },
}
